runtime: nodejs8

# [START handlers]
handlers:
 - url: /
  script: auto
  static_files: build/index.html
  upload: build/index.html
- url: /favicon\.ico
  static_files: build/cayor_icon.ico
  upload: build/cayor_icon.ico
- url: /.*
 script: auto
 static_files: build/\1
   # upload: build/(.*)
# [END handlers]
